version: "3"
services:
  web:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: "redis"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sql5411831
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: sql5.freemysqlhosting.net
      MYSQL_USER: sql5411831
      MYSQL_PASSWORD: KjHuJeWGEV
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
